### ISSUE TITLE
License of this source code and pretrained CRF model 

### ISSUE THREAD

**Issue by SantoshMadhukar** [jsavelka/luima_sbd#1]
Hi,
   We want explore the **LUIMA SBD** model and use it for our Natural Language Processing models on Legal. Can you please say what license this source code and model (with dataset) has.

**Comment by jsavelka** [comment]
Hi,

this is a research project. We released the data set for the research community to be used free of charge for any purposes.

We do not put any restrictions on the use for commercial purposes. Please, note that we do not assume any responsibility either.

We kindly ask for an attribution:
Savelka, Jaromir, Vern R. Walker, Matthias Grabmair and Kevin D. Ashley. "Sentence Boundary Detection in Adjudicatory Decisions in the United States." TAL 58.2 (2017).

I also suggest you rather work with the following repo:
https://github.com/jsavelka/sbd_adjudicatory_dec

I will initiate a talk with my co-authors to place the repo under some license (probably MIT) so that the situation is more transparent.

Best.

Jaromir
