### ISSUE TITLE
Can you provide the training files?

### ISSUE THREAD

**Issue by kdk2612** [jsavelka/luima_sbd#2]
I want to run some additional experiments on this using other tagging schemes, and different parameters. Can you please upload the training or the data-prep code for the same?

**Comment by kdk2612** [comment]
I tried to read the data present in the https://github.com/jsavelka/sbd_adjudicatory_dec repo and using the IOBES scheme - I got the following support 
{'B-sent': 24890,
         'I-sent': 1158318,
         'E-sent': 24890,
         'O': 18577,
         'S-sent': 926}
which is way different from what you have. So wondering what is wrong

**Comment by jsavelka** [comment]
The training files are here https://github.com/jsavelka/sbd_adjudicatory_dec

There might have been some small updates to them after this model was trained. But nothing dramatic.

**Comment by jsavelka** [comment]
Hi. What exactly are you comparing this to?
Best.
j

**Comment by kdk2612** [comment]
Hi, I wanted to train a different model using BERT or Elmo, more recent techniques.
But I am facing issues in reading the data and preparing it. There are tokens with no tags in the data. and the distribution is different from what was mentioned in the paper associated to the library. If you could provide the data prep code, it could be useful.

**Comment by jsavelka** [comment]
Alright. Let us see what we can do. What is the purpose of your work?
Best.
j

**Comment by kdk2612** [comment]
Trying to build a SBD for legal text as a part of sub project.

**Comment by jsavelka** [comment]
Is it research or commercial?

Also, what are you comparing your BILOU tags to that makes you think it is
off?

J

**Comment by kdk2612** [comment]
Its currently research. I am not sure if it'll be commercial for now. But if we do that route, will definitely contact you for the licensing stuff. 
The distribution of tags that I have is - 
for 80 documents
({'B-sent': 25709, 'I-sent': 1154701, 'S-sent': 24787, 'O': 32217})

removing the cyber_crime gives 
for 60 documents
({'B-sent': 17467, 'I-sent': 811623, 'S-sent': 17069, 'O': 23515})

and the one I read in the paper was 
{'B': 25126,'I': 658870, 'L': 26052}

So, i think i am doing something wrong for the data prep, wanted to validate the same.

**Comment by jsavelka** [comment]
Alright, man.

I think the paper you are talking about is not the one that I published for
the data set. The one related to the data set is this:
https://www.atala.org/sites/default/files/2-%20TAL-58-2-sbd-adjudicatory-decisions.pdf


I think what you are referring to is the following one:
https://www.aclweb.org/anthology/W19-2204.pdf

As to your concern, I actually think that your pre-processing is closer to
mine than what they did. First of all, I would think that the number of Bs
and Ls should be the same. If it is not it already points to some sort of
an issue. Second, in my paper I report:
26,052 sentences and 1,237,414 tokens

These numbers are very close to what you are seeing whereas they obviously
used a very different tokenization.

If you can show to me that you are a PhD student pursuing research at a
university I might think about supporting you and give you my code.
Otherwise, I am not comfortable giving it away.

Best.

Jaromir
